### ISSUE TITLE
Ability to "pin" TLS version and/or ciphers

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#13]
It would be nice if you could not only pin the cert hash (https://github.com/lgrahl/threema-msgapi-sdk-python/issues/9), but also the ciphers and the TLS version to use. This would effectively make any downgrade attacks impossible and ensure that always the best encryption is used.

E.g. you can also do this [in the PHP-SDK](https://github.com/rugk/threema-msgapi-sdk-php#creating-a-connection-with-advanced-options).

**Comment by lgrahl** [comment]
I'm in two minds about this. Certainly, a developer should have this option, and in fact he has because no one is required to use this project _as is_. Then again, _good_ TLS settings security change over time and there are plenty of misleading _optimal settings_ out there. I'm quite sure that the developers of aiohttp take this as seriously as we do and they can use their knowledge to provide us sane and safe TLS settings. 

I guess it would be okay to add an optional keyword argument _connector_ to the class _Connection_ which contains a [aiohttp.BaseConnector](https://aiohttp.readthedocs.org/en/stable/client_reference.html#baseconnector) instance. But I wouldn't want to go any further. At least not without some very convincing arguments.

Nevertheless, if somebody wants to do it, the following should work (TLS settings from [this page](https://docs.python.org/3.5/library/ssl.html#ssl-security)). I have not tested this and I'm definitely not recommending it!

``` python
import ssl
import aiohttp

from threema import gateway


class Connection(gateway.Connection):
    def __init__(self, *args, fingerprint=None, verify_fingerprint=False, **kwargs):
        super().__init__(*args, fingerprint=fingerprint,
                         verify_fingerprint=verify_fingerprint, **kwargs)

        # Create your own SSL context here...
        ssl_context = ssl.create_default_context()

        # Override session
        if fingerprint is None and verify_fingerprint:
            fingerprint = self.fingerprint
        connector = aiohttp.TCPConnector(fingerprint=fingerprint, ssl_context=ssl_context)
        self._session = aiohttp.ClientSession(connector=connector)
```

**Comment by rugk** [comment]
Yes I would also only make it optional (that's why I said "ability" :smiley:), so that the user can choose for him/herself the best ciphers and therefore he should know that this might need to be updated at some time.
