### ISSUE TITLE
Allow usage of asyncio.run

### ISSUE THREAD

**Issue by NotANormalNerd** [threema-ch/threema-msgapi-sdk-python#47]
Hey 👋🏻 Maybe you can help me.

Would it be possible to use asyncio.run for execution? Since python3.6 is the last version not to support that, that would be a big improvement for me, since I have to handle the eventloop myself.

https://github.com/python/cpython/blob/d9d63f13cf5b6b896c245099c42b08f6da083d05/Lib/asyncio/runners.py#L8

I haven't got it working with the current code, maybe you can provide some pointers.

**Comment by lgrahl** [comment]
`asyncio.run` should just work :tm:. Maybe I don't understand the question?

**Comment by NotANormalNerd** [comment]
The last time I checked, I had some obscure error, which I couldn't figure out.
I think it has something to do with you approach to the blocking wrappers, which I also couldn't get to work in gunicorn at least.

With `blocking=true` it should also be callable without `asyncio.run` or am I wrong?

**Comment by lgrahl** [comment]
> The last time I checked, I had some obscure error, which I couldn't figure out.

Might be. You could post the stacktrace if you run into that (with a simple reproducible example).

> With `blocking=true` it should also be callable without `asyncio.run` or am I wrong?

Yes. In hindsight, I'm honestly not a fan of the *blocking* mode though. I think async programming has achieved widespread popularity in Python by now (in comparison to a couple years ago), so I might remove it some day.

**Comment by lgrahl** [comment]
Feel free to reopen if it's still an issue.

**Comment by NotANormalNerd** [comment]
One comment regarding the widespread popularity of async in Python:
We are running the SDK as part of a Django Server which is by design blocking.
So when using this SDK without blocking mode we still have to call `run_until_complete` and all the benefits of async are lost. So not having to wrap our heads around async in that case is a big plus.

We could also fork the SDK and do a non-async version but that would just mean maintaining a second version of the code for python. So I think the solution you have found is wonderful and probably works ^^ Especially since you have improved it now.

So if we ever meet (after this whole Corona Situation) I will pay you a nice evening in a bar or pub of your choice.

**Comment by lgrahl** [comment]
I think the issue you had with `asyncio.run` is that it stops the event loop after it completes. Since aiohttp ties itself to the event loop that created the `Connection` instance which is then no longer available, it complains. :slightly_smiling_face:

> So not having to wrap our heads around async in that case is a big plus.

Yeah, I'm fine with having a sync variant of the API. The finicky part at the moment is that the `blocking` argument changes the whole behaviour of the class. If I were to add type hints at some point, writing those would be a nightmare. Once we get to that point, I'll probably remove the `blocking` argument and add a separate `sync` package which proxies all the async classes and functions to be sync.

> So if we ever meet (after this whole Corona Situation) I will pay you a nice evening in a bar or pub of your choice.

Heh, I might remind you of that at some point.

**Comment by NotANormalNerd** [comment]
> Heh, I might remind you of that at some point.

Please do so 😄
