### ISSUE TITLE
Official fork? & What's your plan?

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-python#5]
Looking at this repo confuses me. From the [commit history](https://github.com/lgrahl/threema-msgapi-sdk-python/commit/26c837838b6d0682d03e4f627885e83d433a9617) it seems it was once hosted officially under [`threema-ch\msgapi-sdk-python`](https://github.com/threema-ch/threema-msgapi-sdk-python).
It seems you were a contributor, because afterwards the whole repo was moved here and is deleted at threema-ch. As Threema did not do this with the other repos it is quite confusing.

But anyway it is nice to see that you maintain it here - I'll maintain my [PHP fork](https://github.com/rugk/threema-msgapi-sdk-php) too. There I [choose the approach](https://github.com/rugk/threema-msgapi-sdk-php/wiki/What-to-know-about-this-fork) to have a branch with the official files (just as a mirror) while developing ad Pull Requests on the main branch are possible.
What's you plan?

**Edit:** Related: [Threema hat GitHub Repositories eingestellt](http://threema-forum.de/thread-1381.html)

**Comment by lgrahl** [comment]
I completely understand your confusion. The repo has been moved here because I've been talking to the guys at Threema. They don't want to maintain the _Gateway SDK_ repositories on GitHub anymore which is rather sad but they have their reasons. Because the _Python SDK_ has been written by me in the first place, I've asked them to move it here so I can continue working on it separately to their internal repositories.

**This is still the official _Threema Gateway Python SDK_.** In the near future, the gateway website will probably be updated and simply point to this repository. The plan is to catch up with the other SDK versions. Hosted documentation on https://readthedocs.org and _asyncio_ support would be nice, too. Contributions are warmly welcomed.

**Comment by rugk** [comment]
Okay, it is just a bit confusing that it was directly deleted from threema-ch's account. For my fork I'll just created a PR [to add an information](https://github.com/threema-ch/threema-msgapi-sdk-php/pull/25).

> This is still the official _Threema Gateway Python SDK_.

Well... most people won't consider it so officially - as it is not maintained by Threema (alias @threema-ch anymore).
So maybe an explanation about this in the Readme would be nice.

**Comment by rugk** [comment]
Ah okay just saw you already added a note.

**Comment by rugk** [comment]
Anyway there will be two versions of the Phyton SDK:
- the "official" version: the one downloadable from gateway.threema.ch
- the "official" fork: your version here

AFAIK both version will be developed further. So what do you intend to do? Will you submit the development you do here to to Threema so they can include it in their internal repos?

**Comment by lgrahl** [comment]
No, there will be just one version of the Python SDK maintained here. As I said, all of this has been done in agreement with Threema.

**Comment by rugk** [comment]
Okay, this finally answers my question. :+1:

**Comment by lgrahl** [comment]
Supplement: The [Gateway SDK page for Python](https://gateway.threema.ch/en/developer/sdk-python) has been updated.
